services:
  flask-app:
    image: o.g-s-papertrading-flask-app:0.0.1
    build:
      context: ./flask-app
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    networks:
      - app-network
    environment:
      - FLASK_APP=main.py
    env_file:
      - ./flask-app/.env

  fastapi-app:
    image: o.g-s-papertrading-fastapi-app:0.0.1
    build:
      context: ./fastapi-app
      dockerfile: Dockerfile
    networks:
      - app-network
    environment:
      - FASTAPI_APP=main.py
    env_file:
      - ./fastapi-app/.env
    volumes:
      - ./fastapi-app/https/cert.pem:/etc/ssl/certs/cert.pem
      - ./fastapi-app/https/key.pem:/etc/ssl/certs/key.pem
  
  ngrok:
    image: ngrok/ngrok
    env_file:
      .env
    command: http flask-app:8888
    ports:
      - "4040:4040"
    networks:
      - app-network
    container_name: o.g-s-papertrading-ngrok-tunneler

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.28.0.0/16"