version: '3.8'
services:
  flask-app:
    build:
      context: ./new-papertrading
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    networks:
      - app-network
    environment:
      - FLASK_APP=main.py
    env_file:
      - ./new-papertrading/.env

  fastapi-app:
    build:
      context: ./papertrading
      dockerfile: Dockerfile
    networks:
      - app-network
    environment:
      - FASTAPI_APP=main.py
    env_file:
      - ./papertrading/.env
    volumes:
      - ./papertrading/https/cert.pem:/etc/ssl/certs/cert.pem
      - ./papertrading/https/key.pem:/etc/ssl/certs/key.pem

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.28.0.0/16"